(defun bubble-sort (l)
  (let ((array-version (make-array (length l)))
        (list-len (length l))
        temp)
    (dotimes (pos list-len)
      (setf (aref array-version pos) (nth pos l)))
    (dotimes (x list-len)
      (do ((y 0 (1+ y)))
          ((= (1+ y) list-len) t)
        (when (> (aref array-version y) (aref array-version (1+ y)))
          (setf temp (aref array-version y)
          (aref array-version y) (aref array-version (1+ y))
          (aref array-version (1+ y)) temp))))
    (dotimes (pos list-len)
      (setf (nth pos l) (aref array-version pos)))
    l))
